<script src="js/jquery-3.2.1.min.js"></script>
<!--<script src="js/popper.min.js"> </script>
<script src="js/bootstrap.min.js"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="js/jquery.cookie.js"> </script>
<script src="js/jquery.validate.min.js"></script>
<script src="/js/bootstrap-select.min.js"></script>
<script src="https://d32d8xzgnjxuvk.cloudfront.net/places/1-0/js/owl.carousel.min.js"></script>
<script src="/js/jquery.fancybox.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="js/charts-home.js"></script>
<script src="js/front.js"></script>
